# Configuration for clipboard operations
clipboard_config:
  # Whether to copy the generated responses to your clipboard.
  copy_to_clipboard: true
  # Whether to extract the first code block from the generated response to your clipboard.
  # If this is set to true, the system will only grab what's in triple backticks (```) and ignore everything else in the response.
  copy_from_code_blocks: true
  # Whether to paste the generated responses at the cursor position.
  # If this is set to true, the responses will be inserted at the current cursor position in the active application.
  paste_at_cursor: true

# Configuration for the language model
llm_config:
  # The ID of the language model to use for generating responses.
  llm_id: "llama3"
  # The type of the language model. This can be "ollama", "openai", or "huggingface".
  llm_type: "ollama"
  # The URL of the server where the language model is hosted for "ollama" models.
  server_url: "http://localhost:11434/v1"

# The maximum length of audio recordings, in seconds.
# This setting is used when the system is recording audio input.
max_audio_length_seconds: 3600

# The ID of the model to use for speech-to-text conversion.
# In this case, we're using OpenAI & HuggingFace trained "distil-whisper".
whisper_id: "distil-whisper/distil-small.en"
